### PR TITLE
Add section about planshots to readme

### PR DESCRIPTION
**Pull request by pturley**

### CODE REVIEW

**Review by phoolish — DISMISSED** [review]
This looks good, but I wonder if we need something speaking to how to setup the AWS credentials as well or point to something that can help with that.

**Review by jhanggi — DISMISSED** [review]
Looks good, but yeah, I think adding info on setting up aws creds would be good.

**Comment by pturley** [comment]
@phoolish or @jhanggi cool, I added a bit for that

**Comment by pturley** [comment]
That is @jhanggi's way of approving things these days

**Pull request merged**
