### PR TITLE
ADD optional private subnets

### PR DESCRIPTION
**Pull request by phoolish**
Make private subnets optional (disabled by default)

### CODE REVIEW

**Comment by vandrijevik** [comment]
Can we remove this altogether, or do we need to turn it on somewhere that uses this module?

**Comment by phoolish** [comment]
I am more concerned if we add additional functionality and we need to update older installs that still require a private_subnet. I don't have a specific use case in mind, so I could be persuaded as well.

**Review by vandrijevik — APPROVED** [review]
I’d say rip it out until (if ever) we feel the need, so it forces us to rethink at that point (and maybe find a better solution), but I’m fine either way 😄

**Comment by phoolish** [comment]
The old bandaid approach 🤕

**Review by pturley — APPROVED** [review]
I have a strong emotional urge to agree when someone invokes YAGNI, but I feel like having this here mirrors what AWS suggests you do and allows us to do what we want to do. I dunno, feels good to keep.

**Pull request merged**
