### PR TITLE
EKS: Ignore desired size after initial creation

### PR DESCRIPTION
**Pull request by phoolish**
This is the only way to allow the node group to scale independently of the terraform state. We can use terraform to define the `desired_size` to start, but don't want to impede any other scaling mechanisms.

### CODE REVIEW

**Review by vandrijevik — DISMISSED** [review]
Makes sense to me.

**Comment by vandrijevik** [comment]
@phoolish Heads up, the check here is waiting but not running because https://github.com/tablexi/terraform_modules/pull/194 hasn’t been merged yet: the repo settings expect a passing check, but that PR’s code is not here to tell GitHub Actions how to run.

**Comment by phoolish** [comment]
@vandrijevik would you mind pinging me when that gets merged?

**Comment by vandrijevik** [comment]
@phoolish I just merged the GitHub Actions work, and took the liberty of merging `main` into this branch.

**Pull request merged**
