### PR TITLE
Replace CircleCI format checking with GitHub Actions

### PR DESCRIPTION
**Pull request by vandrijevik**
This PR replaces some a CircleCI definition file for checking the Terraform format, with a GitHub Actions implementation to do the same thing.

It seems that CircleCI did not actually run the job because it was not included in any workflow, so in order to get a passing build, I have also added a commit which fixes the format of files which were reported as ill-formatted by `terraform format`.

### CODE REVIEW

**Review by pturley — APPROVED** [review]
I really like this change, because it feels like we are getting to dip our toes a little bit more into github actions. That being said, I dont know that we have agreed that this is good as a group. So, I think consider my approval here my vote for this.

**Comment by vandrijevik** [comment]
@pturley Thanks for the feedback! Just to make sure I understand what you mean by _this_ in the phrase “agreed that this is good as a group”: are you referring to checking Terraform format being a good thing, or using GitHub Actions being a good thing?

**Comment by pturley** [comment]
Using github actions.

**Comment by vandrijevik** [comment]
@tablexi/devops-core Does anyone object to this PR, or have other thoughts around it?

**Comment by ahorner** [comment]
I prefer having this to not having it, if my vote helps sway movement on this. Given how lightweight the checks are for this repo, using Github actions over CircleCI feels fine to me.

**Comment by phoolish** [comment]
go for it!

**Pull request merged**
