### PR TITLE
Add variable to enable or disable AWS instance termination protection

### PR DESCRIPTION
**Pull request by stephen-puiszis**
https://www.terraform.io/docs/providers/aws/r/instance.html#disable_api_termination

### CODE REVIEW

**Review by pturley — CHANGES_REQUESTED** [review]
This doesnt seem to be used anywhere yet.

**Comment by vandrijevik** [comment]
@stephen-puiszis Can you give some context around why you’re proposing this change, and why you think we should enable instance termination protection by default? I’m familiar with the argument supported by Terraform, but I don’t think that we should enable this on instances that we manage (and certainly not by default).

**Comment by stephen-puiszis** [comment]
@vandrijevik I modified the default value to follow the Terraform and AWS default of `false`

**Comment by vandrijevik** [comment]
@stephen-puiszis Cool! Can you still tell me why we need to add this, though? Since we interact with the AWS API via Terraform, which includes dry run capabilities, and it explicitly asks for confirmation even on `apply` operations, I don’t think that we should be setting this on EC2 instances we manage.

**Comment by stephen-puiszis** [comment]
@vandrijevik Correct. However, this feature also applies instance termination protection in the AWS console. This is something we should have as an option available for managed-client accounts where the client has access to the AWS console (i.e. CounterFind) and to prevent anyone from doing something stupid in the AWS console. I'm not worried about one of us doing anything stupid via `terraform plan`, I'm worried about someone doing something stupid in the console.

**Comment by vandrijevik** [comment]
@stephen-puiszis Has this been a problem in the past? To the best of my knowledge, our clients do not interfere with the infrastructure that we manage on their behalf.

Since termination protection can be turned off by the same person who would go to destroy an EC2 instance, it does not offer assurance but merely a verification step in the process, and I don’t think it is a measure that we should take. EC2 instances are only a part of the infrastructure that we manage, and I don’t think they should have this extra termination verification step (similar to how we don’t enable extra deletion steps on other resources in AWS, like load balancers) because we have checks and reviews elsewhere in our process.

**Pull request closed without merging**
