### PR TITLE
Consolidate EKS code into aws/eks module

### PR DESCRIPTION
**Pull request by vandrijevik**
Adds `aws/eks/cluster` which encapsulates all parts for creating an EKS cluster at Table XI, and is used [like so](https://github.com/tablexi/chef-repo/pull/2955/files#diff-fbf0e3523644bedd9c75e11f7a1103ffR79).

The only interesting trick is [using this `null_resource`](https://github.com/tablexi/terraform_modules/compare/va-add-eks-cluster-module?expand=1#diff-3a8dff24d61d938110aad76040dbf924R11) to simulate `depends_on` between Terraform modules — this is not natively supported, and neither is specifying `depends_on = ["${var.depends_on}"]`, which errors out with a message that depends on can’t contain interpolated values.

To get around this, I create a null resource whose `triggers` includes a no-op value that implicitly depends on the passed-in `depends_on` variable, thus establishing an order of creation in Terraform. As a result, the CloudFormation stack for the EKS nodes (which depends on the null resource, which depends on the passed-in `depends_on` variable, which is set to the endpoint of the EKS master) is created after the EKS cluster, ensuring that the nodes don’t attempt to connect to the control plane before it is fully created.

### CODE REVIEW

**Comment by pturley** [comment]
@vandrijevik if it helps remove some of the gymnastics, you should feel free to merge the master and nodes modules into this one. I dont expect that we will have `cluster` as well as a `master/nodes` module once we get this how we'd like it.

**Comment by vandrijevik** [comment]
@pturley Right now it would mean a bunch more `state mv` calls as we flatten out the modules, but maybe I’ll save that for when we introduce `eks-production` and see if there are even more pieces we want to move into this module to avoid doing them manually!

Update: All of ☝️ is to say I think I’d like to proceed with this PR as-is, and do that refactoring as a separate step (to keep things small gymnastics-wise).

**Comment by pturley** [comment]
@vandrijevik cool, that is your call, but couldn't we just blow away the two clusters right now and rebuild them? I dont know of anything there that cant just be rebuilt easily. Just wanted you to know that you don't have to treat the current clusters like production.

**Comment by vandrijevik** [comment]
@pturley Right on, I did that for `eks-staging` and merged #109 in here. Since AWS EKS announced Kubernetes 1.12 support yesterday, it seemed even more prudent to destroy+recreate the cluster so we’re running on the latest supported version.

I’m still waiting to hear back from folks who may be using `eks-development`, but if that’s okay to recreate as well, I will do so today.

**Review by pturley — APPROVED** [review]
This looks great. I am curious/hopeful that it works

**Comment by vandrijevik** [comment]
> I am curious/hopeful that it works

I destroy+recreated `eks-staging` this morning with it, and after applying `kubectl`, everything worked :)

**Comment by pturley** [comment]
That is great to hear. This is what I originally wanted, but couldn't quite
get to. Woohoo

**Pull request merged**
